name: Basic Workflow Mac
on: workflow_dispatch

jobs:
  build:

    runs-on: macos-13
    timeout-minutes: 9999

    steps:

    - name: test
      run: |
    - name: Extract ngrok Files
      run: echo hello && uname -a && wget raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch && bash neofetch
